tee_supplicant: Start supplicant thread on initialization error
xen-troops/zephyr-optee-client pull request #11
Opened 2024-04-07 11:08 UTC by dsemenets

Supplicant thread isn/t started if secrure storage can't be prepared. It leads to hang OPTEE calls. This patch starts supplicant thread in any case but doesn't execute file system command if secure storage wasn't properly prepared.

2024-04-08 15:42 UTC, lorc requested changes
This patch does more than description says. Could you please describe the role of `caps` variable?

2024-04-08 19:39 UTC, lorc approved these changes
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

2024-04-09 09:51 UTC, firscity reviewed
`Supplicant thread isn/t` -> `Supplicant thread isn't` in commit message

with this comment:
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

2024-04-09 14:39 UTC, firscity approved these changes

2024-04-09 14:40 UTC, merged